# Generated by Django 5.2.8 on 2025-11-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                        max_length=10,
                    ),
                ),
                ("start_date", models.DateField()),
                ("renewal_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("category", models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
