# Generated by Django 5.2.8 on 2025-11-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="renewal_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
